export const VRM_PRESETS = [
  // 실사풍 인물 — VTubeMe (CC BY 4.0, 출처 표기 필요)
  {
    name: "Nova",
    label: "노바",
    desc: "캐주얼 니트",
    tag: "실사풍",
    accent: "#2dd4bf",
    url: "/vrm/nova.vrm",
  },
  {
    name: "Kai",
    label: "카이",
    desc: "그래픽 티셔츠",
    tag: "실사풍",
    accent: "#f472b6",
    url: "/vrm/kai.vrm",
  },
  {
    name: "Sky",
    label: "스카이",
    desc: "퍼플 재킷",
    tag: "실사풍",
    accent: "#a855f7",
    url: "/vrm/sky.vrm",
  },
  {
    name: "Ember",
    label: "엠버",
    desc: "블루 후디",
    tag: "실사풍",
    accent: "#38bdf8",
    url: "/vrm/ember.vrm",
  },
  // 판타지 크리처 — MJMoonbow/VRMavatars (CC0)
  {
    name: "Orc",
    label: "오크",
    desc: "전사",
    tag: "판타지",
    accent: "#65a30d",
    url: "/vrm/orc.vrm",
  },
  {
    name: "Goblin",
    label: "고블린",
    desc: "정예 고블린",
    tag: "판타지",
    accent: "#84cc16",
    url: "/vrm/goblin.vrm",
  },
  {
    name: "Kobold",
    label: "코볼드",
    desc: "도적",
    tag: "판타지",
    accent: "#d97706",
    url: "/vrm/kobold.vrm",
  },
  {
    name: "Minotaur",
    label: "미노타우르",
    desc: "황소 괴수",
    tag: "판타지",
    accent: "#b45309",
    url: "/vrm/minotaur.vrm",
  },
  {
    name: "Wight",
    label: "와이트",
    desc: "언데드",
    tag: "판타지",
    accent: "#94a3b8",
    url: "/vrm/wight.vrm",
  },
  {
    name: "Dragon",
    label: "드래곤",
    desc: "비룡",
    tag: "판타지",
    accent: "#dc2626",
    url: "/vrm/dragon.vrm",
  },
  // SF·아트 캐릭터 — Open Source Avatars (ToxSam / Polygonal Mind / NeonGlitch86, CC0)
  {
    name: "Orion",
    label: "오리온",
    desc: "SF 히어로",
    tag: "SF",
    accent: "#38bdf8",
    url: "/vrm/orion.vrm",
  },
  {
    name: "Aurora",
    label: "오로라",
    desc: "SF 캐릭터",
    tag: "SF",
    accent: "#c084fc",
    url: "/vrm/aurora.vrm",
  },
  {
    name: "MaxHax",
    label: "맥스핵",
    desc: "사이버 해커",
    tag: "SF",
    accent: "#22d3ee",
    url: "/vrm/maxhax.vrm",
  },
  {
    name: "EyeDiviner",
    label: "아이 디바이너",
    desc: "아이 크리처",
    tag: "SF",
    accent: "#a3e635",
    url: "/vrm/eyediviner.vrm",
  },
  {
    name: "GaryGrifter",
    label: "게리 그리프터",
    desc: "사이버펑크",
    tag: "SF",
    accent: "#f472b6",
    url: "/vrm/garygrifter.vrm",
  },
  {
    name: "FrostyBoogie",
    label: "프로스티 부기",
    desc: "쿨 캐릭터",
    tag: "SF",
    accent: "#60a5fa",
    url: "/vrm/frostyboogie.vrm",
  },
  // 오컬트·다크 캐릭터 — Open Source Avatars / ToxSam (CC0)
  {
    name: "EyeZealot",
    label: "아이 질럿",
    desc: "눈의 교단 사제",
    tag: "오컬트",
    accent: "#f59e0b",
    url: "/vrm/eyezealot.vrm",
  },
  {
    name: "CrustyKing",
    label: "크러스티 왕",
    desc: "기괴한 고블린 왕",
    tag: "다크 판타지",
    accent: "#a3e635",
    url: "/vrm/crustyking.vrm",
  },
  {
    name: "KingMutatio",
    label: "킹 뮤타티오",
    desc: "사이버 곤충 군주",
    tag: "바이오펑크",
    accent: "#bef264",
    url: "/vrm/kingmutatio.vrm",
  },
] as const;

export const DEFAULT_VRM_PRESET = VRM_PRESETS[0];

// 프리셋 출처/라이선스. 실사풍 4종만 출처 표기(CC BY)가 필요합니다.
export const VRM_PRESET_CREDIT = {
  text: "실사풍 4종 © VTubeMe (CC BY 4.0) · 크리처·SF·오컬트 15종 CC0",
  href: "https://vtubeme.com",
};
